<a href="https://colab.research.google.com/github/vishakha711/Machine-Learning/blob/main/Fake_news_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Problem Statement :**

### Fake News Detection with the help of Natural Language Processing Technique.

### **Required Libraries**

In [ ]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split

nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

### **Data Gathering**

In [ ]:
df = pd.read_csv("/content/WELFake_Dataset.csv.zip")
df.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

### **Data Analysis**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72134 entries, 0 to 72133
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  72134 non-null  int64
 1   title       71576 non-null  object
 2   text        72095 non-null  object
 3   label       72134 non-null  int64
dtypes: int64(2), object(2)
memory usage: 2.2+ MB

In [ ]:
df['label'].value_counts()

label
1    37106
0    35028
Name: count, dtype: int64

In [ ]:
df.shape

(72134, 4)

In [ ]:
df.isna().sum()  #To check missing values

Unnamed: 0      0
title         558
text           39
label           0
dtype: int64

In [ ]:
df = df.dropna() #handle missing value by drop function

In [ ]:
df.isna().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [ ]:
df.shape

(71537, 4)

In [ ]:
df.reset_index(inplace=True)
df.head()

,index,Unnamed: 0,title,text,label
0,0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
2,3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
3,4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
4,5,5,About Time! Christian Group Sues Amazon and SP...,All we can say on this one is it s about time ...,1

In [ ]:
df = df.drop(['text'],axis = 1)

### **Data Preprocessing**

In [ ]:
lm = WordNetLemmatizer()
corpus = []
for i in range(0,len(df)):
  review = re.sub('[^a-zA-Z0-9]',' ', df['title'][i])
  review = review.lower()  #lowercase
  review = review.split()  #Tokenization
  review = [lm.lemmatize(x) for x in review if x not in stopwords.words('english')] #remove stopwards and lemmatization
  review = ' '.join(review)  #join syntax
  corpus.append(review)

In [ ]:
len(corpus)

71537

In [ ]:
df['title'][0]

'LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO]'

In [ ]:
corpus[0]

'law enforcement high alert following threat cop white 9 11by blacklivesmatter fyf911 terrorist video'

### **Vectorization**

In [ ]:
tf = TfidfVectorizer()
x = tf.fit_transform(corpus)
x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 635275 stored elements and shape (71537, 26218)>

In [ ]:
y= df['label']
y.head()

0    1
1    1
2    0
3    1
4    1
Name: label, dtype: int64

### **Data splitting into the train and test**

In [ ]:

x_train, x_test,y_train, y_test = train_test_split(x,y, test_size = 0.3,random_state = 10,stratify = y)

In [ ]:
x_train.shape[0], len(y_train)

(50075, 50075)

In [ ]:
x_test.shape[0], len(y_test)

(21462, 21462)

### **Model Building**

In [ ]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

### **Model Evaluation**

In [ ]:
y_pred = rf.predict(x_test)
accuracy_score = accuracy_score(y_test,y_pred)
accuracy_score

0.9004752585965893

In [ ]:
class Evaluation:
  def __init__(self,model,x_train,x_test,y_train,y_test):
    self.model = model
    self.x_train = x_train
    self.x_test = x_test
    self.y_train = y_train
    self.y_test = y_test

  def train_evaluation(self):
    y_pred_train = self.model.predict(self.x_train)
    acc_scr_train = accuracy_score(self.y_train,y_pred_train)
    print("Accuracy Score On Training Data Set :",acc_scr_train)
    print()

    con_mat_train = confusion_matrix(self.y_train,y_pred_train)
    print("Confusion Matrix On Training Data Set :\n",con_mat_train)
    print()

    class_rep_train = classification_report(self.y_train,y_pred_train)
    print("Classification On Training Data Set :\n",class_rep_train)
    print()

  def test_evaluation(self):
    y_pred_test = self.model.predict(self.x_test)
    acc_scr_train = accuracy_score(self.y_test,y_pred_test)
    print("Accuracy Score On Testing Data Set :",acc_scr_train)
    print()

    con_mat_train = confusion_matrix(self.y_test,y_pred_test)
    print("Confusion Matrix On Testing Data Set :\n",con_mat_train)
    print()

    class_rep_train = classification_report(self.y_test,y_pred_test)
    print("Classification On Testing Data Set :\n",class_rep_train)
    print()

In [ ]:
#Checking the accuracy on training dataset
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
Evaluation(rf,x_train, x_test, y_train, y_test).train_evaluation()

Accuracy Score On Training Data Set : 0.9998801797304044

Confusion Matrix On Training Data Set :
 [[24516     3]
 [    3 25553]]

Classification On Training Data Set :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     24519
           1       1.00      1.00      1.00     25556

    accuracy                           1.00     50075
   macro avg       1.00      1.00      1.00     50075
weighted avg       1.00      1.00      1.00     50075

In [ ]:
#Checking the accuracy on testing dataset
Evaluation(rf,x_train, x_test, y_train, y_test).test_evaluation()

Accuracy Score On Testing Data Set : 0.9004752585965893

Confusion Matrix On Testing Data Set :
 [[ 9254  1255]
 [  881 10072]]

Classification On Testing Data Set :
               precision    recall  f1-score   support

           0       0.91      0.88      0.90     10509
           1       0.89      0.92      0.90     10953

    accuracy                           0.90     21462
   macro avg       0.90      0.90      0.90     21462
weighted avg       0.90      0.90      0.90     21462

### **Prediction Pipeline**

In [ ]:
class Preprocessing:
  def __init__(self,data):
    self.data = data

  def text_preprocessing_user(self):
    lm = WordNetLemmatizer()
    pred_data = [self.data]
    preprocess_data = []
    for data in pred_data:
      review = re.sub('[^a-zA-Z0-9]',' ', data)
      review = review.lower()  #lowercase
      review = review.split()  #Tokenization
      review = [lm.lemmatize(x) for x in review if x not in stopwords.words('english')] #remove stopwards and lemmatization
      review = ' '.join(review)  #join syntax
      preprocess_data.append(review)
    return preprocess_data

In [ ]:
df['title'][0]

'LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO]'

In [ ]:
data = 'LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO]'
Preprocessing(data).text_preprocessing_user()

['law enforcement high alert following threat cop white 9 11by blacklivesmatter fyf911 terrorist video']

In [ ]:
class Prediction:
  def __init__(self,pred_data,model):
    self.pred_data = pred_data
    self.model = model

  def prediction_model(self):
    preprocess_data = Preprocessing(self.pred_data).text_preprocessing_user()
    data = tf.transform(preprocess_data)
    prediction = self.model.predict(data)

    if prediction [0] == 0:
      return "The News Is Fake"
    else:
      return "The News Is Real"

In [ ]:
data = 'LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO]'
Prediction(data,rf).prediction_model()

'The News Is Real'

In [ ]:
df['title'][3]

'SATAN 2: Russia unvelis an image of its terrifying new ‘SUPERNUKE’ – Western world takes notice'

In [ ]:
user_data = 'SATAN 2: Russia unvelis an image of its terrifying new ‘SUPERNUKE’ – Western world takes notice'
Prediction(user_data,rf).prediction_model()

'The News Is Real'